from __future__ import annotations

import copy
from pathlib import Path

import pytest

from owner_research.calculation_integrity import (
    build_calculation_result,
)
from owner_research.capital_allocation_policies import economic_event_key
from owner_research.component_lock import file_sha256
from owner_research.contracts import contract_from_dict
from owner_research.fingerprints import canonical_sha256
from owner_research.valuation_handoff_policies import (
    assumption_evidence_policy_sha256,
    assumption_slot_policy_sha256,
    empty_supplemental_reference_closure_sha256,
    legacy_handoff_v2_kernel_identity,
    price_blind_freeze_policy_sha256,
)

ROOT = Path(__file__).parents[1]


@pytest.fixture
def sample_payloads() -> dict[str, dict]:
    payloads = {
        "source-document": {
            "schema_version": "1.0.0",
            "document_id": "doc:acme:2025-10k",
            "issuer_id": "issuer:acme",
            "document_type": "10-K",
            "period": {"start": "2025-01-01", "end": "2025-12-31"},
            "published_date": "2026-02-15",
            "retrieved_at": "2026-02-16T01:02:03Z",
            "source_url": "https://example.com/acme-10k",
            "authority_level": "primary_regulatory",
            "content_sha256": "a" * 64,
        },
        "fact": {
            "schema_version": "2.0.0",
            "fact_id": "fact:acme:revenue:2025",
            "issuer_id": "issuer:acme",
            "concept": "revenue",
            "value_type": "number",
            "value": 1250.0,
            "unit": "currency_millions",
            "currency": "USD",
            "period": {"start": "2025-01-01", "end": "2025-12-31"},
            "source_document_id": "doc:acme:2025-10k",
            "source_locator": "p. 47, Consolidated Statements of Operations",
            "derivation": None,
            "parent_fact_ids": [],
            "confidence": "high",
        },
        "claim": {
            "schema_version": "1.0.0",
            "claim_id": "claim:acme:revenue-growth",
            "issuer_id": "issuer:acme",
            "statement": "Reported revenue increased during fiscal 2025.",
            "as_of_date": "2026-02-16",
            "supporting_fact_ids": ["fact:acme:revenue:2025"],
            "counterevidence_fact_ids": [],
            "counterevidence_search_note": "Searched the same filing for restatements and offsets.",
            "confidence": "medium",
            "falsification_condition": "A later restatement reverses the reported increase.",
        },
        "assumption": {
            "schema_version": "1.0.0",
            "assumption_id": "assumption:acme:base-growth",
            "issuer_id": "issuer:acme",
            "concept": "revenue_growth",
            "value_type": "number",
            "value": 0.05,
            "unit": "ratio",
            "currency": "USD",
            "horizon": {"start": "2026-01-01", "end": "2030-12-31"},
            "scenario": "base",
            "rationale": "A bounded assumption for contract testing only.",
            "supporting_fact_ids": ["fact:acme:revenue:2025"],
            "supporting_claim_ids": ["claim:acme:revenue-growth"],
            "confidence": "low",
        },
        "calculation-result": {
            "schema_version": "2.0.0",
            "calculation_id": "calc:acme:test-growth",
            "issuer_id": "issuer:acme",
            "concept": "test_growth",
            "value_type": "number",
            "value": 0.05,
            "unit": "ratio",
            "currency": "USD",
            "period": {"start": "2026-01-01", "end": "2030-12-31"},
            "generator": "deterministic_program",
            "calculator_id": "contract-test",
            "calculator_version": "1.0.0",
            "code_sha256": "b" * 64,
            "input_fact_ids": ["fact:acme:revenue:2025"],
            "input_assumption_ids": ["assumption:acme:base-growth"],
            "input_calculation_ids": [],
            "input_period_ids": [],
            "input_bindings": {},
            "input_fingerprint": "0" * 64,
            "output_fingerprint": "0" * 64,
            "generated_at": "2026-02-16T02:00:00Z",
        },
        "score": {
            "schema_version": "1.0.0",
            "score_id": "score:acme:test-quality",
            "issuer_id": "issuer:acme",
            "extension_label": "PROJECT_EXTENSION",
            "framework": "owner-research-test",
            "component": "evidence_quality",
            "score": 8.0,
            "max_score": 10.0,
            "rationale": "Fixture demonstrating one-way evidence consumption.",
            "fact_ids": ["fact:acme:revenue:2025"],
            "claim_ids": ["claim:acme:revenue-growth"],
            "calculation_result_ids": ["calc:acme:test-growth"],
            "confidence": "medium",
            "missing_evidence": ["Independent market-share series"],
            "red_flags": ["Single-period evidence"],
        },
        "report-spec": {
            "schema_version": "1.0.0",
            "report_spec_id": "report-spec:owner-research-v1",
            "language": "zh-CN",
            "audience": "long_term_owner",
            "sections": [
                {
                    "section_id": "evidence",
                    "title": "证据与缺口",
                    "required_input_types": ["Fact", "Claim"],
                }
            ],
            "output_formats": ["json"],
            "partial_and_blocked_states_required": True,
        },
        "run-manifest": {
            "schema_version": "1.0.0",
            "run_id": "run:acme:2026-02-16",
            "issuer_id": "issuer:acme",
            "data_cutoff_date": "2026-02-15",
            "started_at": "2026-02-16T01:00:00Z",
            "completed_at": "2026-02-16T02:30:00Z",
            "component_lock_sha256": file_sha256(ROOT / "component-lock.json"),
            "component_versions": {"owner-equity-research": "0.4.0-alpha.1"},
            "input_document_hashes": {"doc:acme:2025-10k": "a" * 64},
            "output_artifact_hashes": {"research-package.json": "f" * 64},
            "missing_evidence": ["Independent market-share series"],
            "anti_anchoring": {
                "state": "pre_conclusion",
                "conclusion_frozen_at": None,
                "current_conclusion_sha256": None,
                "prior_materials_accessed": [],
            },
        },
        "research-bundle": {
            "schema_version": "1.0.0",
            "bundle_id": "research-bundle:issuer:acme:2026-02-15:00000000000000000000",
            "issuer_id": "issuer:acme",
            "data_cutoff_date": "2026-02-15",
            "bundle_policy_id": "research-bundle",
            "bundle_policy_version": "1.0.0",
            "status": "blocked",
            "module_references": [
                {
                    "module_type": module_type,
                    "object_ids": [],
                    "module_status": "blocked",
                    "as_of_date": "2026-02-15",
                    "period": None,
                    "scope": {
                        "scope_id": "scope:issuer:acme:issuer-wide",
                        "scope_type": "issuer_wide",
                        "segment_definition_ids": [],
                        "business_unit": None,
                        "product_service": None,
                        "geography": None,
                        "customer_group": None,
                        "channel": None,
                    },
                    "freshness": {
                        "status": "blocked",
                        "event_watermark_date": None,
                        "qualifying_source_document_ids": [],
                        "missing_evidence": ["Module evidence not integrated"],
                    },
                    "artifact_sha256": "0" * 64,
                    "missing_evidence": ["Module evidence not integrated"],
                }
                for module_type in (
                    "quarterly_update",
                    "segment_snapshot",
                    "footnote_review",
                    "accounting_quality_review",
                    "management_review",
                    "business_quality_review",
                    "capital_allocation_review",
                )
            ],
            "source_document_ids": [],
            "fiscal_period_ids": [],
            "segment_definition_ids": [],
            "source_graph_sha256": "0" * 64,
            "dependency_closure_sha256": "0" * 64,
            "component_lock_sha256": file_sha256(ROOT / "component-lock.json"),
            "bundle_fingerprint": "0" * 64,
            "run_id": "run:acme:2026-02-16",
            "missing_evidence": ["Module evidence not integrated"],
        },
        "valuation-assumption-candidate": {
            "schema_version": "2.0.0",
            "candidate_id": "valuation-candidate:acme:base-revenue:2026",
            "issuer_id": "issuer:acme",
            "data_cutoff_date": "2026-02-15",
            "candidate_policy_id": "valuation-assumption-candidate",
            "candidate_policy_version": "2.0.0",
            "research_bundle_id": "research-bundle:issuer:acme:2026-02-15:00000000000000000000",
            "research_bundle_fingerprint": "0" * 64,
            "research_bundle_dependency_sha256": "0" * 64,
            "supplemental_reference_closure_sha256": (
                empty_supplemental_reference_closure_sha256()
            ),
            "assumption_slot_id": "mckinsey.base.forecast.2026.revenue",
            "method_scope": "mckinsey",
            "kernel_concept": "revenue",
            "value": 1300.0,
            "unit": "currency_millions",
            "currency": "USD",
            "horizon": {
                "kind": "period",
                "start_date": "2026-01-01",
                "end_date": "2026-12-31",
            },
            "scenario": "base",
            "rationale": "Price-blind contract fixture supported by reported revenue.",
            "evidence_bindings": [
                {
                    "binding_id": "valuation-evidence:acme:base-revenue",
                    "role": "support",
                    "slot_evidence_role": "mapped_historical_fact",
                    "evidence_domain": "research_bundle",
                    "contract_type": "Fact",
                    "object_id": "fact:acme:revenue:2025",
                }
            ],
            "generation_method": "human",
            "evidence_graph_sha256": "1" * 64,
            "validation_status": "eligible",
            "validation_issues": [],
        },
        "valuation-assumption-review-decision": {
            "schema_version": "1.0.0",
            "decision_id": "valuation-decision:acme:base-revenue:2026",
            "issuer_id": "issuer:acme",
            "candidate_id": "valuation-candidate:acme:base-revenue:2026",
            "candidate_fingerprint": "0" * 64,
            "evidence_graph_sha256": "1" * 64,
            "decision": "confirmed",
            "reserved_kernel_assumption_id": "kernel-assumption:acme:base-revenue:2026",
            "supersedes_decision_id": None,
            "reviewer_type": "human",
            "reviewer_id": "reviewer:phase5a",
            "reviewed_at": "2026-02-16T03:00:00Z",
            "rationale": "Candidate semantics and evidence binding were reviewed.",
            "issues": [],
        },
        "market-reference-snapshot": {
            "schema_version": "3.0.0",
            "snapshot_id": "market-reference:acme:2026-02-13:v3",
            "issuer_id": "issuer:acme",
            "data_cutoff_date": "2026-02-15",
            "status": "validated",
            "market_policy_id": "market-reference",
            "market_policy_version": "3.0.0",
            "authorization_handoff_id": "valuation-handoff:acme:run-1:v4",
            "authorization_handoff_fingerprint": "0" * 64,
            "component_lock_sha256": file_sha256(ROOT / "component-lock.json"),
            "market_access_result_fingerprint": "1" * 64,
            "market_quote_request": {
                "request_id": "market-request:acme:2026-02-13",
                "request_fingerprint": "2" * 64,
            },
            "governed_market_quote_receipt": {
                "receipt_id": "market-receipt:acme:2026-02-13",
                "receipt_fingerprint": "3" * 64,
            },
            "authority_lineage": {
                "authority_sha256": "4" * 64,
                "provider_registry_sha256": "5" * 64,
                "provider_registration_sha256": "6" * 64,
                "adapter_sha256": "7" * 64,
                "parser_sha256": "8" * 64,
                "calendar_registry_sha256": "9" * 64,
                "calendar_dataset_sha256": "a" * 64,
                "calendar_selection_fingerprint": "b" * 64,
            },
            "security": {
                "security_id": "security:acme:common",
                "ticker": "ACME",
                "mic": "XNYS",
                "share_class": "common",
                "security_compilation_fingerprint": "c" * 64,
                "security_evidence_closure_sha256": "d" * 64,
            },
            "trading_date": "2026-02-13",
            "quote_timestamp": "2026-02-13T21:00:00Z",
            "quote_retrieved_at": "2026-02-16T03:05:00Z",
            "quote_price_decimal": "50",
            "quote_unit": "currency_per_share",
            "quote_currency": "USD",
            "evidence_mode": "recorded_fixture",
            "usage_scope": "test_only",
            "raw_evidence": {
                "store_kind": "repository_fixture",
                "locator": "repo://tests/fixtures/phase5e2a/recorded-official-close.json",
                "content_type": "application/json",
                "raw_response_sha256": "e" * 64,
                "parser_replay_fingerprint": "f" * 64,
            },
            "quote_source_document_id": "doc:acme:market:2026-02-13",
            "quote_source_locator": "market://request/receipt/parser",
            "quote_fact_id": "fact:acme:market:2026-02-13",
            "share_basis": {
                "decision_id": "share-basis-decision:acme:2026-02-13",
                "decision_fingerprint": "0" * 64,
                "basis_kind": "current_common_shares_outstanding",
                "evidence_kind": "direct_point_in_time",
                "as_of_date": "2026-02-13",
                "quote_date": "2026-02-13",
                "shares_outstanding_fact_id": "fact:acme:current-common-shares:2026-02-13",
                "current_common_shares_outstanding_decimal": "100000000",
                "share_unit": "shares",
                "split_factor_decimal": "1",
                "corporate_action_evidence_bindings": [
                    {
                        "contract_type": "SourceDocument",
                        "object_id": "doc:acme:2025-10k",
                        "fingerprint": "1" * 64,
                    }
                ],
                "claim_control_check": {
                    "status": "passed",
                    "current_share_numeric_root_fact_ids": [
                        "fact:acme:current-common-shares:2026-02-13"
                    ],
                    "included_claim_root_fact_ids": [],
                    "excluded_claim_root_fact_ids": [],
                    "blocked_claim_root_fact_ids": [],
                    "overlap_fact_ids": [],
                    "check_fingerprint": "2" * 64,
                },
            },
            "market_equity": {
                "calculation_id": "calc:acme:market-equity:2026-02-13",
                "value_decimal": "5000000000",
                "unit": "currency_units",
                "currency": "USD",
            },
            "price_blind_input_fingerprint": "3" * 64,
            "protected_mckinsey_sha256": "4" * 64,
            "protected_penman_assumptions_sha256": "5" * 64,
            "future_kernel_request_v2": {
                "share_denominator_fact_id": "fact:acme:current-common-shares:2026-02-13",
                "share_denominator_kind": "current_common_shares_outstanding",
                "share_denominator_evidence_kind": "direct_point_in_time",
                "mapping_fingerprint": "7" * 64,
            },
            "market_evidence_closure_sha256": "6" * 64,
            "snapshot_fingerprint": "0" * 64,
        },
        "valuation-handoff": {
            "schema_version": "2.0.0",
            "handoff_id": "valuation-handoff:acme:run-1:v1",
            "handoff_policy_id": "valuation-handoff",
            "handoff_policy_version": "2.0.0",
            "handoff_run_id": "valuation-run:acme:1",
            "handoff_version": 1,
            "transitioned_at": "2026-02-16T03:05:00Z",
            "issuer_id": "issuer:acme",
            "data_cutoff_date": "2026-02-15",
            "state": "evidence_open",
            "predecessor_handoff_id": None,
            "supersedes_handoff_id": None,
            "research_bundle_id": "research-bundle:issuer:acme:2026-02-15:00000000000000000000",
            "research_bundle_fingerprint": "0" * 64,
            "research_bundle_dependency_sha256": "0" * 64,
            "research_run_manifest_id": "run:acme:2026-02-16",
            "supplemental_reference_closure_sha256": (
                empty_supplemental_reference_closure_sha256()
            ),
            "mapping_policy_id": "phase5-mapping-boundary",
            "mapping_policy_version": "1.0.0",
            "assumption_slot_policy_id": "assumption-slot",
            "assumption_slot_policy_version": "1.0.0",
            "assumption_slot_policy_sha256": assumption_slot_policy_sha256(),
            "assumption_evidence_policy_id": "assumption-evidence",
            "assumption_evidence_policy_version": "1.0.0",
            "assumption_evidence_policy_sha256": assumption_evidence_policy_sha256(),
            "price_blind_freeze_policy_id": "price-blind-freeze",
            "price_blind_freeze_policy_version": "1.0.0",
            "price_blind_freeze_policy_sha256": price_blind_freeze_policy_sha256(),
            "component_lock_sha256": file_sha256(ROOT / "component-lock.json"),
            "kernel_identity": {},
            "assumption_candidate_ids": [],
            "assumption_review_decision_ids": [],
            "price_blind_input_fingerprint": None,
            "protected_mckinsey_sha256": None,
            "protected_penman_assumptions_sha256": None,
            "market_reference_snapshot_id": None,
            "valuation_request_sha256": None,
            "valuation_result_sha256": None,
            "quarantined_market_reference_snapshot_ids": [],
            "missing_evidence": ["Valuation evidence mapping has not started"],
        },
        "fiscal-period": {
            "schema_version": "1.0.0",
            "period_id": "period:acme:2025-q4",
            "issuer_id": "issuer:acme",
            "fiscal_year": 2025,
            "fiscal_quarter": 4,
            "calendar_type": "calendar",
            "quarter_start": "2025-10-01",
            "quarter_end": "2025-12-31",
            "cumulative_start": "2025-01-01",
            "cumulative_end": "2025-12-31",
            "ttm_start": "2025-01-01",
            "weeks": 13,
            "comparative_period_id": None,
            "restatement_version": 0,
            "status": "reported",
            "source_document_ids": ["doc:acme:2025-10k"],
        },
        "quarterly-reconciliation": {
            "schema_version": "1.0.0",
            "reconciliation_id": "reconciliation:acme:revenue:2025-q4",
            "issuer_id": "issuer:acme",
            "period_id": "period:acme:2025-q4",
            "basis": "ytd",
            "concept": "revenue",
            "candidate_fact_ids": [
                "fact:acme:revenue:2025",
                "fact:acme:revenue:release",
            ],
            "authoritative_fact_id": "fact:acme:revenue:2025",
            "delta_calculation_id": "calc:acme:test-growth",
            "tolerance": 0.01,
            "status": "exact_match",
            "selection_rule": "regulatory_over_company_release",
            "blocked": False,
            "notes": "Regulatory filing matches the company release.",
        },
        "quarterly-update": {
            "schema_version": "1.0.0",
            "update_id": "quarterly-update:acme:2025-q4",
            "issuer_id": "issuer:acme",
            "as_of_date": "2026-02-16",
            "current_period_id": "period:acme:2025-q4",
            "comparison_period_id": "period:acme:2024-q4",
            "status": "blocked",
            "comparability": {"status": "comparable", "reasons": []},
            "fact_ids": ["fact:acme:revenue:2025"],
            "calculation_result_ids": ["calc:acme:test-growth"],
            "reconciliation_ids": ["reconciliation:acme:revenue:2025-q4"],
            "what_changed_claim_ids": ["claim:acme:revenue-growth"],
            "why_it_changed_claim_ids": [],
            "temporary_or_structural_claim_ids": [],
            "guidance_change_claim_ids": [],
            "long_term_thesis_impact_claim_ids": [],
            "impact_on_valuation_assumptions_claim_ids": [],
            "valuation_assumption_review_required": False,
            "confidence": "medium",
            "missing_evidence": ["Comparison-period quarterly contract"],
            "red_flags": [],
        },
        "filing-artifact": {
            "schema_version": "1.0.0",
            "artifact_id": "filing:acme:2025-10k",
            "issuer_id": "issuer:acme",
            "source_document_id": "doc:acme:2025-10k",
            "cik": "0001018724",
            "accession": "0001018724-26-000001",
            "form": "10-K",
            "filing_date": "2026-02-15",
            "report_period": "2025-12-31",
            "primary_document": "acme-20251231.html",
            "source_url": "https://www.sec.gov/Archives/edgar/data/1018724/filing.html",
            "raw_sha256": "1" * 64,
            "normalized_sha256": "2" * 64,
            "parser_id": "owner-research-sec",
            "parser_version": "0.3.0-alpha.1",
            "retrieved_at": "2026-02-16T01:02:03Z",
        },
        "extraction-candidate": {
            "schema_version": "1.0.0",
            "candidate_id": "candidate:acme:revenue",
            "issuer_id": "issuer:acme",
            "source_document_id": "doc:acme:2025-10k",
            "artifact_id": "filing:acme:2025-10k",
            "candidate_kind": "numeric_fact",
            "concept": "revenue",
            "value_type": "number",
            "value": 1250.0,
            "unit": "currency_millions",
            "currency": "USD",
            "period": {"start": "2025-01-01", "end": "2025-12-31"},
            "dimensions": {"segment": "Cloud"},
            "locator": {"kind": "ixbrl_context", "value": "c-cloud", "excerpt_sha256": "3" * 64},
            "extraction_method": "deterministic_ixbrl",
            "extractor_id": "owner-research-ixbrl",
            "extractor_version": "0.3.0-alpha.1",
            "validation_status": "validated",
            "validation_issues": [],
            "high_impact": False,
        },
        "evidence-promotion": {
            "schema_version": "1.0.0",
            "promotion_id": "promotion:acme:revenue",
            "issuer_id": "issuer:acme",
            "candidate_id": "candidate:acme:revenue",
            "candidate_fingerprint": "4" * 64,
            "decision": "auto_fact",
            "output_fact_id": "fact:acme:revenue:2025",
            "output_claim_id": None,
            "approval_kind": "deterministic_program",
            "policy_id": "owner-research-evidence-promotion",
            "policy_version": "1.0.0",
            "checks": {
                "primary_regulatory": True,
                "locator_resolved": True,
                "hash_resolved": True,
                "value_resolved": True,
                "unit_resolved": True,
                "currency_resolved": True,
                "period_resolved": True,
                "duplicates_resolved": True,
                "reconciliation_resolved": True,
            },
            "reviewed_at": "2026-02-16T02:00:00Z",
            "reviewer_id": None,
            "rationale": "All automatic promotion gates passed.",
            "issues": [],
        },
        "segment-definition": {
            "schema_version": "1.0.0",
            "segment_id": "segment:acme:cloud",
            "issuer_id": "issuer:acme",
            "disclosed_name": "Cloud",
            "normalized_name": "cloud",
            "segment_type": "reportable",
            "effective_period": {"start": "2025-01-01", "end": "2025-12-31"},
            "source_document_ids": ["doc:acme:2025-10k"],
            "predecessor_segment_ids": [],
            "mapping_status": "exact",
            "mapping_claim_id": None,
        },
        "segment-snapshot": {
            "schema_version": "1.0.0",
            "snapshot_id": "segment-snapshot:acme:2025",
            "issuer_id": "issuer:acme",
            "fiscal_period_id": "period:acme:2025-q4",
            "status": "partial",
            "segment_definition_ids": ["segment:acme:cloud"],
            "metric_assignments": [
                {
                    "segment_id": "segment:acme:cloud",
                    "fact_id": "fact:acme:revenue:2025",
                    "metric_role": "revenue",
                    "presentation_order": 0,
                }
            ],
            "consolidated_fact_ids": ["fact:acme:revenue:2025"],
            "reconciliation_calculation_ids": [],
            "display_precision": {
                "unit": "currency_millions",
                "currency": "USD",
                "rounding_increment": 1.0,
            },
            "comparability_claim_ids": [],
            "missing_evidence": ["Segment profit not disclosed"],
        },
        "footnote-review": {
            "schema_version": "1.0.0",
            "review_id": "footnote:acme:sbc",
            "issuer_id": "issuer:acme",
            "fiscal_period_id": "period:acme:2025-q4",
            "topic_code": "sbc",
            "dynamic_topic_label": None,
            "status": "reviewed",
            "source_document_ids": ["doc:acme:2025-10k"],
            "candidate_ids": [],
            "fact_ids": ["fact:acme:revenue:2025"],
            "claim_ids": ["claim:acme:revenue-growth"],
            "calculation_result_ids": [],
            "missing_evidence": [],
            "counterevidence_search_note": "Reviewed the filing and amendment index.",
        },
        "accounting-quality-finding": {
            "schema_version": "1.0.0",
            "finding_id": "finding:acme:sbc",
            "issuer_id": "issuer:acme",
            "rule_id": "sbc-dilution",
            "rule_version": "1.0.0",
            "category": "sbc_dilution",
            "suggested_severity": "watch",
            "final_severity": "watch",
            "classification": "structural",
            "status": "confirmed",
            "fact_ids": ["fact:acme:revenue:2025"],
            "calculation_result_ids": [],
            "claim_ids": ["claim:acme:revenue-growth"],
            "override_claim_id": None,
            "missing_evidence": [],
        },
        "accounting-quality-review": {
            "schema_version": "1.0.0",
            "review_id": "quality-review:acme:2025",
            "issuer_id": "issuer:acme",
            "fiscal_period_id": "period:acme:2025-q4",
            "status": "partial",
            "rule_set_version": "1.0.0",
            "required_topic_codes": [
                "revenue_contract_balances",
                "sbc",
                "leases",
                "income_taxes",
                "pensions_postretirement",
                "goodwill_intangibles_impairment",
                "debt_liquidity_covenants",
                "contingencies_litigation",
                "acquisitions_divestitures",
                "restructuring_exit",
                "related_parties",
                "commitments_guarantees_off_balance_sheet",
                "supplier_finance",
                "vie",
                "fair_value_derivatives_hedging",
            ],
            "footnote_review_ids": [f"footnote:acme:{i}" for i in range(15)],
            "finding_ids": ["finding:acme:sbc"],
            "coverage": {
                "required_count": 15,
                "reviewed_count": 14,
                "not_disclosed_count": 0,
                "not_applicable_count": 0,
                "blocked_count": 1,
            },
            "missing_evidence": ["One topic is blocked"],
        },
        "business-model-snapshot": {
            "schema_version": "3.0.0",
            "snapshot_id": "business-model:acme:2025",
            "issuer_id": "issuer:acme",
            "as_of_date": "2026-02-16",
            "status": "blocked",
            "source_document_ids": ["doc:acme:2025-10k"],
            "segment_snapshot_ids": ["segment-snapshot:acme:2025"],
            "material_scopes": [
                {
                    "scope_id": "business-scope:issuer:acme:4b4e134f144e9ac0b678",
                    "scope": {
                        "scope_type": "issuer_wide",
                        "segment_definition_ids": [],
                        "business_unit": None,
                        "product_service": None,
                        "geography": None,
                        "customer_group": None,
                        "channel": None,
                    },
                    "derivation": "single_reportable_segment",
                    "segment_snapshot_id": "segment-snapshot:acme:2025",
                    "segment_definition_ids": ["segment:acme:cloud"],
                    "materiality_claim_id": None,
                }
            ],
            "components": [
                {
                    "component_id": "component:acme:customer",
                    "component_type": "customer",
                    "scope_id": "business-scope:issuer:acme:4b4e134f144e9ac0b678",
                    "scope": {
                        "scope_type": "issuer_wide",
                        "segment_definition_ids": [],
                        "business_unit": None,
                        "product_service": None,
                        "geography": None,
                        "customer_group": None,
                        "channel": None,
                    },
                    "attribute_roles": ["customer_identity"],
                    "attribute_evidence_bindings": [
                        {
                            "binding_id": "attribute-binding:acme:customer-identity",
                            "role": "customer_identity",
                            "fact_ids": ["fact:acme:revenue:2025"],
                            "claim_ids": ["claim:acme:revenue-growth"],
                            "review_decision_ids": [
                                "analytical-review:acme:revenue-growth"
                            ],
                        }
                    ],
                    "fact_ids": ["fact:acme:revenue:2025"],
                    "claim_ids": ["claim:acme:revenue-growth"],
                }
            ],
            "component_coverage": [
                {
                    "scope_id": "business-scope:issuer:acme:4b4e134f144e9ac0b678",
                    "component_type": component_type,
                    "status": "blocked",
                    "component_ids": (
                        ["component:acme:customer"] if component_type == "customer" else []
                    ),
                    "claim_ids": [],
                    "review_decision_ids": [],
                    "missing_evidence": ["Component evidence remains incomplete"],
                }
                for component_type in (
                    "customer",
                    "value_proposition",
                    "revenue_model",
                    "cost_structure",
                    "distribution",
                    "key_resource",
                    "key_partner",
                    "regulatory_dependency",
                )
            ],
            "shared_scope_relations": [],
            "missing_evidence": ["Complete business-model component coverage"],
        },
        "context-observation": {
            "schema_version": "1.0.0",
            "observation_id": "context-observation:acme:product-market",
            "target_issuer_id": "issuer:acme",
            "subject": {
                "entity_id": "issuer:acme",
                "entity_name": "Acme",
                "role": "target_issuer",
            },
            "as_of_date": "2026-02-16",
            "scope": {
                "scope_type": "issuer_wide",
                "segment_definition_ids": [],
                "business_unit": None,
                "product_service": None,
                "geography": None,
                "customer_group": None,
                "channel": None,
            },
            "observation_type": "product_market",
            "statement": "Acme reports one disclosed product market.",
            "value_type": "none",
            "value": None,
            "unit": None,
            "currency": None,
            "period": {"start": "2025-01-01", "end": "2025-12-31"},
            "source_document_id": "doc:acme:2025-10k",
            "source_locator": "Item 1",
            "extraction_method": "manual",
            "verification_status": "human_confirmed",
            "reviewer_id": "reviewer:phase4c",
            "reviewed_at": "2026-02-16T03:00:00Z",
            "confidence": "medium",
            "limitations": [],
        },
        "competitive-context-snapshot": {
            "schema_version": "1.0.0",
            "context_snapshot_id": "competitive-context:acme:2025",
            "issuer_id": "issuer:acme",
            "as_of_date": "2026-02-16",
            "status": "partial",
            "scope": {
                "scope_type": "issuer_wide",
                "segment_definition_ids": [],
                "business_unit": None,
                "product_service": None,
                "geography": None,
                "customer_group": None,
                "channel": None,
            },
            "source_document_ids": ["doc:acme:2025-10k"],
            "observation_ids": ["context-observation:acme:product-market"],
            "competitor_selection_claim_ids": ["claim:acme:revenue-growth"],
            "coverage": [
                {
                    "topic": topic,
                    "status": "reviewed" if topic == "product_service" else "blocked",
                    "observation_ids": (
                        ["context-observation:acme:product-market"]
                        if topic == "product_service"
                        else []
                    ),
                    "claim_ids": [],
                    "missing_evidence": (
                        [] if topic == "product_service" else ["Context topic not reviewed"]
                    ),
                }
                for topic in (
                    "product_service",
                    "customer_group",
                    "geography",
                    "channel",
                    "competitor_set",
                    "substitutes",
                    "entry_barriers",
                    "buyer_power",
                    "supplier_power",
                    "rivalry",
                    "regulatory_change",
                    "technology_change",
                    "market_growth",
                )
            ],
            "missing_evidence": ["Twelve competitive-context topics remain blocked"],
        },
        "analytical-claim-candidate": {
            "schema_version": "2.0.0",
            "candidate_id": "analytical-candidate:acme:revenue-growth",
            "issuer_id": "issuer:acme",
            "as_of_date": "2026-02-16",
            "proposed_statement": "Reported revenue increased during fiscal 2025.",
            "scope": {
                "scope_type": "issuer_wide",
                "segment_definition_ids": [],
                "business_unit": None,
                "product_service": None,
                "geography": None,
                "customer_group": None,
                "channel": None,
            },
            "claim_role": "support",
            "business_attribute_role": "customer_identity",
            "business_component_type": "customer",
            "supporting_evidence_bindings": [
                {
                    "binding_id": "binding:acme:revenue",
                    "fact_id": "fact:acme:revenue:2025",
                    "calculation_result_id": None,
                    "context_observation_id": None,
                }
            ],
            "counterevidence_bindings": [],
            "counterevidence_search_note": "Searched the same filing for restatements and offsets.",
            "proposed_confidence": "medium",
            "falsification_condition": "A later restatement reverses the reported increase.",
            "generation_method": "language_model",
            "evidence_graph_sha256": "0" * 64,
            "validation_status": "ready",
            "validation_issues": [],
        },
        "analytical-claim-review-decision": {
            "schema_version": "1.0.0",
            "decision_id": "analytical-review:acme:revenue-growth",
            "issuer_id": "issuer:acme",
            "candidate_id": "analytical-candidate:acme:revenue-growth",
            "candidate_fingerprint": "0" * 64,
            "evidence_graph_sha256": "0" * 64,
            "decision": "confirmed",
            "output_claim_id": "claim:acme:revenue-growth",
            "reviewer_id": "reviewer:phase4c",
            "reviewed_at": "2026-02-16T03:00:00Z",
            "rationale": "Evidence and falsification boundary confirmed.",
            "issues": [],
        },
        "competitive-advantage-hypothesis": {
            "schema_version": "2.0.0",
            "hypothesis_id": "hypothesis:acme:switching-cost",
            "issuer_id": "issuer:acme",
            "as_of_date": "2026-02-16",
            "assessment_period": {"start": "2025-01-01", "end": "2025-12-31"},
            "mechanism": "switching_cost",
            "mechanism_policy_id": "switching_cost",
            "mechanism_policy_version": "1.0.0",
            "scope": {
                "scope_type": "issuer_wide",
                "segment_definition_ids": [],
                "business_unit": None,
                "product_service": None,
                "geography": None,
                "customer_group": None,
                "channel": None,
            },
            "status": "blocked",
            "business_model_snapshot_id": "business-model:acme:2025",
            "competitive_context_snapshot_id": "competitive-context:acme:2025",
            "hypothesis_claim_id": "claim:acme:revenue-growth",
            "durability_claim_id": None,
            "reinvestment_claim_id": None,
            "counterevidence_claim_ids": [],
            "claim_review_decision_ids": ["analytical-review:acme:revenue-growth"],
            "evidence_bindings": [
                {
                    "binding_id": "binding:acme:retention-evidence",
                    "role_id": "retention_churn",
                    "polarity": "support",
                    "fact_id": "fact:acme:revenue:2025",
                    "calculation_result_id": None,
                    "context_observation_id": None,
                }
            ],
            "counterevidence_resolutions": [],
            "reinvestment_relevance": "unknown",
            "predecessor_hypothesis_id": None,
            "trend": "unknown",
            "trend_claim_id": None,
            "missing_evidence": ["Customer retention cohort"],
        },
        "business-quality-review": {
            "schema_version": "2.0.0",
            "review_id": "business-quality:acme:2025",
            "issuer_id": "issuer:acme",
            "review_period": {"start": "2025-01-01", "end": "2025-12-31"},
            "as_of_date": "2026-02-16",
            "status": "blocked",
            "business_model_snapshot_id": "business-model:acme:2025",
            "competitive_context_snapshot_id": "competitive-context:acme:2025",
            "hypothesis_ids": ["hypothesis:acme:switching-cost"],
            "mechanism_coverage": [
                {
                    "mechanism": mechanism,
                    "status": "blocked",
                    "hypothesis_ids": (
                        ["hypothesis:acme:switching-cost"] if mechanism == "switching_cost" else []
                    ),
                    "claim_ids": (
                        ["claim:acme:revenue-growth"] if mechanism == "switching_cost" else []
                    ),
                    "missing_evidence": [
                        (
                            "Switching-cost hypothesis is blocked"
                            if mechanism == "switching_cost"
                            else "Mechanism not reviewed"
                        )
                    ],
                }
                for mechanism in (
                    "switching_cost",
                    "network_effect",
                    "scale_cost_advantage",
                    "brand_pricing_power",
                    "intellectual_property",
                    "regulatory_license",
                    "distribution",
                    "data_learning",
                    "efficient_scale",
                    "process_execution",
                )
            ],
            "claim_ids": ["claim:acme:revenue-growth"],
            "analytical_claim_review_decision_ids": [
                "analytical-review:acme:revenue-growth"
            ],
            "context_observation_ids": ["context-observation:acme:product-market"],
            "calculation_result_ids": [],
            "coverage": {
                "reviewed_component_count": 0,
                "not_applicable_component_count": 0,
                "blocked_component_count": 8,
                "proposed_hypothesis_count": 0,
                "supported_hypothesis_count": 0,
                "contested_hypothesis_count": 0,
                "falsified_hypothesis_count": 0,
                "blocked_hypothesis_count": 1,
                "strengthening_count": 0,
                "stable_count": 0,
                "eroding_count": 0,
                "unknown_trend_count": 1,
                "confirmed_claim_count": 1,
                "unresolved_counterevidence_count": 0,
            },
            "missing_evidence": ["Nine mechanisms remain blocked"],
        },
        "management-statement": {
            "schema_version": "2.0.0",
            "statement_id": "statement:acme:guidance:2026",
            "issuer_id": "issuer:acme",
            "speaker_name": "Alex Executive",
            "speaker_role": "Chief Executive Officer",
            "statement_date": "2026-02-15",
            "statement_type": "guidance",
            "kpi_concept": None,
            "definition_change": "not_applicable",
            "source_document_id": "doc:acme:2025-10k",
            "source_locator": "text:10:67",
            "statement_text": "We expect revenue growth of 5% to 7% in fiscal 2026.",
            "statement_sha256": "a" * 64,
            "extraction_method": "deterministic",
            "verification_status": "pending",
            "reviewer_id": None,
            "reviewed_at": None,
            "lifecycle_status": "current",
            "predecessor_statement_ids": [],
            "kpi_definition_fact_ids": [],
            "commitment_eligibility": "measurable",
            "metric_bindings": [
                {
                    "component_id": "primary",
                    "metric_concept": "revenue_growth",
                    "role": "lower_bound",
                    "fact_id": "fact:acme:revenue-growth-lower:2026",
                },
                {
                    "component_id": "primary",
                    "metric_concept": "revenue_growth",
                    "role": "upper_bound",
                    "fact_id": "fact:acme:revenue-growth-upper:2026",
                },
            ],
            "missing_evidence": ["Human confirmation"],
        },
        "management-statement-candidate": {
            "schema_version": "1.0.0",
            "candidate_id": "management-candidate:issuer:acme:guidance:2026",
            "issuer_id": "issuer:acme",
            "source_document_id": "doc:acme:2025-10k",
            "source_locator": "text:10:67",
            "excerpt_sha256": "a" * 64,
            "statement_text": "We expect revenue growth of 5% to 7% in fiscal 2026.",
            "statement_sha256": "a" * 64,
            "speaker_name": "Alex Executive",
            "speaker_role": "Chief Executive Officer",
            "statement_date": "2026-02-15",
            "statement_type": "guidance",
            "kpi_concept": None,
            "extraction_method": "deterministic",
            "metric_mentions": [
                {
                    "component_id": "primary",
                    "metric_concept": "revenue_growth",
                    "role": "lower_bound",
                    "value_type": "number",
                    "value": 0.05,
                    "unit": "ratio",
                    "currency": None,
                    "period": {"start": "2026-01-01", "end": "2026-12-31"},
                    "scope": {
                        "scope_type": "issuer",
                        "scope_id": "issuer:acme",
                        "scope_label": "Acme consolidated",
                    },
                    "measurement_basis": {
                        "accounting_basis": "gaap",
                        "currency_basis": "reported",
                        "growth_basis": "reported",
                        "aggregation_basis": "period",
                    },
                },
                {
                    "component_id": "primary",
                    "metric_concept": "revenue_growth",
                    "role": "upper_bound",
                    "value_type": "number",
                    "value": 0.07,
                    "unit": "ratio",
                    "currency": None,
                    "period": {"start": "2026-01-01", "end": "2026-12-31"},
                    "scope": {
                        "scope_type": "issuer",
                        "scope_id": "issuer:acme",
                        "scope_label": "Acme consolidated",
                    },
                    "measurement_basis": {
                        "accounting_basis": "gaap",
                        "currency_basis": "reported",
                        "growth_basis": "reported",
                        "aggregation_basis": "period",
                    },
                },
            ],
            "validation_status": "validated",
            "validation_issues": [],
        },
        "management-statement-review-decision": {
            "schema_version": "1.0.0",
            "decision_id": "statement-review:issuer:acme:guidance:2026",
            "issuer_id": "issuer:acme",
            "candidate_id": "management-candidate:issuer:acme:guidance:2026",
            "candidate_fingerprint": "a" * 64,
            "decision": "confirmed",
            "output_statement_id": "statement:acme:guidance:2026",
            "output_fact_ids": [
                "fact:acme:revenue-growth-lower:2026",
                "fact:acme:revenue-growth-upper:2026",
            ],
            "reviewer_id": "reviewer:phase4a",
            "reviewed_at": "2026-02-16T03:00:00Z",
            "rationale": "Confirmed against the exact official filing text.",
            "issues": [],
        },
        "management-commitment": {
            "schema_version": "2.0.0",
            "commitment_id": "commitment:acme:revenue:2026",
            "issuer_id": "issuer:acme",
            "statement_id": "statement:acme:guidance:2026",
            "commitment_type": "guidance",
            "commitment_strength": "committed",
            "metric_concept": "revenue_growth",
            "baseline_bindings": [
                {"component_id": "primary", "fact_id": "fact:acme:revenue:2025"}
            ],
            "target_bindings": [
                {
                    "component_id": "primary",
                    "role": "lower_bound",
                    "fact_id": "fact:acme:revenue-growth-lower:2026",
                },
                {
                    "component_id": "primary",
                    "role": "upper_bound",
                    "fact_id": "fact:acme:revenue-growth-upper:2026",
                },
            ],
            "scope": {
                "scope_type": "issuer",
                "scope_id": "issuer:acme",
                "scope_label": "Acme consolidated",
            },
            "measurement_basis": {
                "accounting_basis": "gaap",
                "currency_basis": "reported",
                "growth_basis": "reported",
                "aggregation_basis": "period",
            },
            "comparison_direction": "exact",
            "start_date": "2026-01-01",
            "due_date": "2026-12-31",
            "evaluation_policy_id": "growth_range",
            "evaluation_policy_version": "1.0.0",
            "condition_claim_ids": [],
            "definition_reconciliation_calculation_ids": [],
            "status": "open",
            "withdrawal_statement_id": None,
            "superseded_by_commitment_id": None,
            "missing_evidence": [],
        },
        "management-outcome": {
            "schema_version": "2.0.0",
            "outcome_id": "management-outcome:acme:revenue:2026",
            "issuer_id": "issuer:acme",
            "commitment_id": "commitment:acme:revenue:2026",
            "predecessor_outcome_id": None,
            "assessed_at": "2026-06-30",
            "evaluation_period": {"start": "2026-01-01", "end": "2026-06-30"},
            "status": "pending",
            "result_bindings": [],
            "result_scope": {
                "scope_type": "issuer",
                "scope_id": "issuer:acme",
                "scope_label": "Acme consolidated",
            },
            "result_measurement_basis": {
                "accounting_basis": "gaap",
                "currency_basis": "reported",
                "growth_basis": "reported",
                "aggregation_basis": "period",
            },
            "claim_ids": ["claim:acme:revenue-growth"],
            "missing_evidence": ["Commitment is not due"],
        },
        "capital-allocation-event-candidate": {
            "schema_version": "2.0.0",
            "candidate_id": "capital-candidate:acme:buyback:2026:10k",
            "issuer_id": "issuer:acme",
            "as_of_date": "2026-02-16",
            "source_document_id": "doc:acme:2025-10k",
            "source_locator": "Item 5, issuer purchases",
            "excerpt_sha256": "c" * 64,
            "proposed_event_type": "buyback",
            "proposed_event_subtype": "open_market",
            "proposed_scope": {
                "scope_type": "issuer_wide",
                "segment_definition_ids": [],
                "business_unit": None,
                "product_service": None,
                "geography": None,
                "customer_group": None,
                "channel": None,
            },
            "proposed_identity_components": [
                {"role": "program_id", "value": "2026 repurchase authorization"},
                {"role": "approval_date", "value": "2026-02-15"},
                {"role": "security_class", "value": "common stock"},
            ],
            "proposed_announcement_date": "2026-02-15",
            "proposed_execution_period": {"start": None, "end": None},
            "proposed_growth_classification": "not_applicable",
            "proposed_source_role": "authorization",
            "proposed_fact_bindings": [],
            "proposed_rationale_statement_ids": [],
            "proposed_related_commitment_ids": [],
            "potential_duplicate_candidate_ids": [],
            "supersedes_candidate_ids": [],
            "extraction_method": "language_model",
            "validation_status": "ready",
            "validation_issues": [],
        },
        "capital-allocation-event-review-decision": {
            "schema_version": "1.0.0",
            "decision_id": "capital-decision:acme:buyback:2026:10k",
            "issuer_id": "issuer:acme",
            "candidate_id": "capital-candidate:acme:buyback:2026:10k",
            "candidate_fingerprint": "d" * 64,
            "decision": "confirmed",
            "output_event_id": "capital-event:acme:buyback:2026",
            "output_economic_event_key": "e" * 64,
            "supersedes_decision_ids": [],
            "reviewer_id": "reviewer:phase4d0",
            "reviewed_at": "2026-02-16T04:00:00Z",
            "rationale": "Official authorization identity and source role confirmed.",
            "issues": [],
        },
        "capital-allocation-event": {
            "schema_version": "2.0.0",
            "event_id": "capital-event:acme:buyback:2026",
            "issuer_id": "issuer:acme",
            "event_policy_id": "capital-allocation-event/buyback",
            "event_policy_version": "1.0.0",
            "economic_event_key": "e" * 64,
            "event_version": 1,
            "predecessor_event_id": None,
            "supersedes_event_ids": [],
            "event_type": "buyback",
            "event_subtype": "open_market",
            "scope": {
                "scope_type": "issuer_wide",
                "segment_definition_ids": [],
                "business_unit": None,
                "product_service": None,
                "geography": None,
                "customer_group": None,
                "channel": None,
            },
            "identity_components": [
                {"role": "program_id", "value": "2026 repurchase authorization"},
                {"role": "approval_date", "value": "2026-02-15"},
                {"role": "security_class", "value": "common stock"},
            ],
            "announcement_date": "2026-02-15",
            "execution_period": {"start": None, "end": None},
            "lifecycle_status": "announced",
            "source_bindings": [
                {
                    "binding_id": "capital-source-binding:acme:buyback:authorization",
                    "candidate_id": "capital-candidate:acme:buyback:2026:10k",
                    "decision_id": "capital-decision:acme:buyback:2026:10k",
                    "source_document_id": "doc:acme:2025-10k",
                    "role_id": "authorization",
                }
            ],
            "fact_bindings": [],
            "claim_bindings": [],
            "rationale_statement_ids": [],
            "related_commitment_ids": [],
            "growth_classification": "not_applicable",
            "missing_evidence": ["Execution results"],
        },
        "capital-allocation-outcome": {
            "schema_version": "2.0.0",
            "outcome_id": "capital-outcome:acme:buyback:2026",
            "issuer_id": "issuer:acme",
            "outcome_policy_id": "capital-allocation-outcome/buyback",
            "outcome_policy_version": "1.0.0",
            "event_id": "capital-event:acme:buyback:2026",
            "predecessor_outcome_id": None,
            "assessed_at": "2026-06-30",
            "observation_period": {"start": "2026-02-15", "end": "2026-06-30"},
            "status": "not_due",
            "result_bindings": [],
            "result_role_coverage": [
                {
                    "role_id": role,
                    "status": "not_due",
                    "binding_ids": [],
                    "claim_binding_ids": [],
                    "missing_evidence": [],
                }
                for role in (
                    "cash_spent",
                    "shares_repurched",
                    "sbc_shares_issued",
                    "other_equity_shares_issued",
                    "basic_shares_change",
                    "diluted_shares_change",
                )
            ],
            "claim_bindings": [],
            "missing_evidence": ["Execution remains pending"],
        },
        "management-review": {
            "schema_version": "2.0.0",
            "review_id": "management-review:acme:2026",
            "issuer_id": "issuer:acme",
            "review_period": {"start": "2026-01-01", "end": "2026-06-30"},
            "as_of_date": "2026-06-30",
            "status": "partial",
            "statement_ids": ["statement:acme:guidance:2026"],
            "commitment_ids": ["commitment:acme:revenue:2026"],
            "outcome_ids": ["management-outcome:acme:revenue:2026"],
            "coverage": {
                "statement_count": 1,
                "confirmed_count": 0,
                "open_count": 1,
                "not_due_count": 1,
                "due_count": 0,
                "evaluated_due_count": 0,
                "pending_count": 1,
                "met_count": 0,
                "partially_met_count": 0,
                "missed_count": 0,
                "unverifiable_count": 0,
                "blocked_count": 0,
                "withdrawn_count": 0,
                "superseded_count": 0,
            },
            "claim_ids": ["claim:acme:revenue-growth"],
            "calculation_result_ids": [],
            "missing_evidence": ["Human confirmation of management statement"],
        },
        "source-search-receipt": {
            "schema_version": "1.0.0",
            "receipt_id": "source-search:acme:10k:2026-h1",
            "issuer_id": "issuer:acme",
            "source_family": "10-K",
            "query_scope": {
                "cik": "0000000123",
                "event_types": [
                    "organic_capex", "research_and_development", "acquisition",
                    "divestiture", "buyback", "dividend", "debt_issuance",
                    "debt_repayment", "equity_issuance", "stock_based_compensation",
                    "pension_funding", "restructuring", "cash_accumulation",
                ],
            },
            "period": {"start": "2026-01-01", "end": "2026-06-30"},
            "cutoff_date": "2026-06-30",
            "searched_endpoints": ["sec:submissions"],
            "result_document_ids": ["doc:acme:2025-10k"],
            "completed_at": "2026-07-01T00:00:00Z",
            "tool_version": "phase4d5-fixture/1.0.0",
            "request_fingerprint": "0" * 64,
            "status": "completed",
            "issues": [],
        },
        "capital-allocation-review": {
            "schema_version": "3.0.0",
            "review_id": "capital-review:acme:2026",
            "issuer_id": "issuer:acme",
            "review_policy_id": "capital-allocation-review",
            "review_policy_version": "2.0.0",
            "review_period": {"start": "2026-01-01", "end": "2026-06-30"},
            "as_of_date": "2026-06-30",
            "status": "blocked",
            "source_coverage": [
                {
                    "source_family": family,
                    "status": "reviewed_present" if family == "10-K" else "blocked",
                    "source_document_ids": ["doc:acme:2025-10k"] if family == "10-K" else [],
                    "search_receipt_ids": (
                        ["source-search:acme:10k:2026-h1"] if family == "10-K" else []
                    ),
                    "claim_binding_ids": [],
                    "missing_evidence": [] if family == "10-K" else [f"{family} not reviewed"],
                }
                for family in (
                    "10-K", "10-Q", "8-K", "DEF14A", "registration_or_prospectus",
                    "tender_or_merger_material", "credit_or_indentures", "official_ir",
                )
            ],
            "event_type_coverage": [
                {
                    "event_type": event_type,
                    "status": "reviewed" if event_type == "buyback" else "blocked",
                    "event_ids": (
                        ["capital-event:acme:buyback:2026"]
                        if event_type == "buyback"
                        else []
                    ),
                    "source_document_ids": ["doc:acme:2025-10k"] if event_type == "buyback" else [],
                    "search_receipt_ids": ["source-search:acme:10k:2026-h1"],
                    "claim_binding_ids": [],
                    "missing_evidence": (
                        [] if event_type == "buyback" else [f"{event_type} not reviewed"]
                    ),
                }
                for event_type in (
                    "organic_capex", "research_and_development", "acquisition", "divestiture",
                    "buyback", "dividend", "debt_issuance", "debt_repayment", "equity_issuance",
                    "stock_based_compensation",
                    "pension_funding",
                    "restructuring",
                    "cash_accumulation",
                )
            ],
            "event_ids": ["capital-event:acme:buyback:2026"],
            "outcome_ids": ["capital-outcome:acme:buyback:2026"],
            "coverage": {
                "logical_event_count": 1,
                "event_version_count": 1,
                "outcome_count": 1,
                "not_due_count": 1,
                "observed_count": 0,
                "partial_count": 0,
                "unverifiable_count": 0,
                "blocked_count": 0,
                "cancelled_count": 0,
                "superseded_count": 0,
                "reviewed_type_count": 1,
                "not_found_type_count": 0,
                "not_applicable_type_count": 0,
                "blocked_type_count": 12,
                "reviewed_present_source_count": 1,
                "searched_not_found_source_count": 0,
                "not_applicable_source_count": 0,
                "blocked_source_count": 7,
            },
            "claim_bindings": [],
            "calculation_result_ids": [],
            "missing_evidence": ["Buyback execution results"],
        },
    }
    payloads["valuation-handoff"]["kernel_identity"] = legacy_handoff_v2_kernel_identity()
    valuation_candidate = contract_from_dict(
        "valuation-assumption-candidate", payloads["valuation-assumption-candidate"]
    )
    payloads["valuation-assumption-review-decision"][
        "candidate_fingerprint"
    ] = valuation_candidate.fingerprint
    fact = contract_from_dict("fact", payloads["fact"])
    assumption = contract_from_dict("assumption", payloads["assumption"])
    calculation = build_calculation_result(
        payloads["calculation-result"],
        facts={fact.fact_id: fact},
        assumptions={assumption.assumption_id: assumption},
        calculations={},
    )
    payloads["calculation-result"] = calculation.to_dict()
    analytical_candidate = payloads["analytical-claim-candidate"]
    analytical_candidate["evidence_graph_sha256"] = canonical_sha256(
        {
            "supporting_evidence_bindings": analytical_candidate[
                "supporting_evidence_bindings"
            ],
            "counterevidence_bindings": analytical_candidate["counterevidence_bindings"],
        }
    )
    candidate_contract = contract_from_dict(
        "analytical-claim-candidate", analytical_candidate
    )
    decision = payloads["analytical-claim-review-decision"]
    decision["candidate_fingerprint"] = candidate_contract.fingerprint
    decision["evidence_graph_sha256"] = analytical_candidate["evidence_graph_sha256"]
    capital_candidate = contract_from_dict(
        "capital-allocation-event-candidate",
        payloads["capital-allocation-event-candidate"],
    )
    capital_key = economic_event_key(
        issuer_id=capital_candidate.issuer_id,
        event_type=capital_candidate.proposed_event_type,
        event_subtype=capital_candidate.proposed_event_subtype,
        identity_components=capital_candidate.proposed_identity_components,
    )
    capital_decision = payloads["capital-allocation-event-review-decision"]
    capital_decision["candidate_fingerprint"] = capital_candidate.fingerprint
    capital_decision["output_economic_event_key"] = capital_key
    payloads["capital-allocation-event"]["economic_event_key"] = capital_key
    receipt = payloads["source-search-receipt"]
    receipt["request_fingerprint"] = canonical_sha256(
        {
            "issuer_id": receipt["issuer_id"],
            "source_family": receipt["source_family"],
            "query_scope": receipt["query_scope"],
            "period": receipt["period"],
            "cutoff_date": receipt["cutoff_date"],
            "searched_endpoints": receipt["searched_endpoints"],
            "tool_version": receipt["tool_version"],
        }
    )
    market_snapshot = payloads["market-reference-snapshot"]
    market_snapshot["snapshot_fingerprint"] = canonical_sha256(
        {key: value for key, value in market_snapshot.items() if key != "snapshot_fingerprint"}
    )
    return copy.deepcopy(payloads)
